services:
  # A Docker web service
  - type: web
    name: djangoEmpty
    env: docker
    repo: https://github.com/yaseen1998/djangoEmpty.git  
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: master # optional (defaults to master)
    rootDir: djangoEmpty
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 3 # optional (defaults to 1)
    healthCheckPath: /
  