
services:
  - type: web
    name: core
    env: python
    buildCommand: pip3 install -r requirements.txt && python manage.py migrate --no-input
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: WEB_CONCURRENCY
        value: 4