databases:
  - name: db
    databaseName: db
    user: db
services:
  # A Docker web service
  - type: web
    name: djangoEmpty
    env: docker
    repo: https://github.com/yaseen1998/djangoEmpty.git  
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: master # optional (defaults to master)
    rootDir: djangoEmpty
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 3 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  